#!/usr/bin/env python3
"""
build_shared.py — generate shared design-token artifacts from tokens.json (ADR 0002).

tokens.json is the single source of truth for the colors used by BOTH frontends
(desktop pages/ and mobile/site/). This generates:

    shared/tokens.css   CSS custom properties (--type-*, --cat-*) for either frontend to <link>.

Both frontends should consume the CSS variables instead of hardcoding hex values, so a
color changes in exactly one place. Migration of the existing pages is incremental.

Usage:
    python3 shared/build_shared.py           # (re)generate tokens.css
    python3 shared/build_shared.py --check    # verify tokens.css is in sync (CI); non-zero on drift

Standard library only.
"""
import os, json, sys, argparse

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "tokens.json")
CSS_OUT = os.path.join(ROOT, "tokens.css")


def render_css(tokens):
    lines = [
        "/* GENERATED by shared/build_shared.py from tokens.json — do not edit by hand. */",
        "/* Single source of truth for type/category colors (ADR 0002). */",
        ":root {",
        "  /* node types */",
    ]
    for t in tokens["types"].values():
        lines.append(f'  --type-{t["slug"]}: {t["color"]};')
    lines.append("  /* place categories */")
    for slug, c in tokens["categories"].items():
        lines.append(f'  --cat-{slug}: {c["color"]};')
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 if tokens.css is out of sync with tokens.json")
    args = ap.parse_args()

    with open(SRC, encoding="utf-8") as f:
        tokens = json.load(f)
    css = render_css(tokens)

    if args.check:
        cur = open(CSS_OUT, encoding="utf-8").read() if os.path.exists(CSS_OUT) else None
        if cur != css:
            print("DRIFT: shared/tokens.css is out of sync — run `python3 shared/build_shared.py`.")
            return 1
        print("shared/tokens.css is in sync.")
        return 0

    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write(css)
    print(f"wrote {os.path.relpath(CSS_OUT, ROOT)} "
          f"({len(tokens['types'])} types, {len(tokens['categories'])} categories)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
